#Papercut MF Server with Mobility Print

# escape=`
FROM microsoft/windowsservercore:latest

#Expose Ports
EXPOSE 53 80 443 5353 9163 9164 9191 9192 9193

ENTRYPOINT ["C:\\ServiceMonitor.exe", "w3svc"]
